### ISSUE TITLE
Invalid subscription handle

### ISSUE THREAD

**Issue by lrporder** [ivosturm/EditableByCondition#4]
Used in 7.12, with microflow, not entity/attribute, page won't open and throws javascript error in browser console:
`EditableByCondition_widget_EditableByCondition_1.applyContext: Error: Trying to unsubscribe using an invalid subscription handle`
Maybe I'm not doing it right?

**Comment by TomFranckaert** [comment]
Hi, I'm having the same issue, using version 7.21
"Trying to unsubscribe using an invalid subscription handle"
I tried with both microflow and boolean attribute.

**Comment by ivosturm** [comment]
Hi, this issue should be resolved with version 1.4.0 I just released in the Mendix AppStore. Let me know if the update worked for you!

**Comment by ivosturm** [comment]
Hi Tom,

Could you check again? I upgraded the widget to version 1.4.0 and just published it in the AppStore.

Can you let me know whether this new version fixes the problem?

Kind regards,
Ivo

Van: Tom <notifications@github.com>
Verzonden: donderdag 7 februari 2019 14:46
Aan: ivosturm/EditableByCondition <EditableByCondition@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [ivosturm/EditableByCondition] Invalid subscription handle (#4)


Hi, I'm having the same issue, using version 7.21
"Trying to unsubscribe using an invalid subscription handle"
I tried with both microflow and boolean attribute.

**Comment by TomFranckaert** [comment]
Thanks man,
Works like a sharm now!
Tom.

**Comment by ivosturm** [comment]
Closing this topic now.
